# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_odm}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Carlos Paramio"]
  s.date = %q{2011-01-20}
  s.description = %q{mongo_odm is a flexible persistence module for any Ruby class to MongoDB.}
  s.email = %q{carlos@evolve.st}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CONTRIBUTORS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/mongo_odm.rb",
    "lib/mongo_odm/collection.rb",
    "lib/mongo_odm/config.rb",
    "lib/mongo_odm/core_ext/conversions.rb",
    "lib/mongo_odm/criteria.rb",
    "lib/mongo_odm/cursor.rb",
    "lib/mongo_odm/document.rb",
    "lib/mongo_odm/document/attribute_methods.rb",
    "lib/mongo_odm/document/attribute_methods/dirty.rb",
    "lib/mongo_odm/document/attribute_methods/inspect.rb",
    "lib/mongo_odm/document/attribute_methods/localization.rb",
    "lib/mongo_odm/document/attribute_methods/query.rb",
    "lib/mongo_odm/document/attribute_methods/read.rb",
    "lib/mongo_odm/document/attribute_methods/write.rb",
    "lib/mongo_odm/document/callbacks.rb",
    "lib/mongo_odm/document/equality.rb",
    "lib/mongo_odm/document/fields.rb",
    "lib/mongo_odm/document/inspect.rb",
    "lib/mongo_odm/document/persistence.rb",
    "lib/mongo_odm/document/timestamps.rb",
    "lib/mongo_odm/document/validations.rb",
    "lib/mongo_odm/errors.rb",
    "lib/mongo_odm/railtie.rb",
    "lib/mongo_odm/version.rb",
    "spec/models/00-blank_slate.rb",
    "spec/models/01-shape.rb",
    "spec/models/02-circle.rb",
    "spec/models/03-big_red_circle.rb",
    "spec/mongo_odm/collection_spec.rb",
    "spec/mongo_odm/config_spec.rb",
    "spec/mongo_odm/core_ext/conversions_spec.rb",
    "spec/mongo_odm/cursor_spec.rb",
    "spec/mongo_odm/document/attribute_methods/dirty_spec.rb",
    "spec/mongo_odm/document/attribute_methods/localization_spec.rb",
    "spec/mongo_odm/document/attribute_methods/query_spec.rb",
    "spec/mongo_odm/document/attribute_methods/read_spec.rb",
    "spec/mongo_odm/document/attribute_methods/write_spec.rb",
    "spec/mongo_odm/document/attribute_methods_spec.rb",
    "spec/mongo_odm/document/callbacks_spec.rb",
    "spec/mongo_odm/document/fields_spec.rb",
    "spec/mongo_odm/document/inspect_spec.rb",
    "spec/mongo_odm/document/persistence_spec.rb",
    "spec/mongo_odm/document/timestamps_spec.rb",
    "spec/mongo_odm/document/validations_spec.rb",
    "spec/mongo_odm/document_spec.rb",
    "spec/mongo_odm/mongo_odm_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/carlosparamio/mongo_odm}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{mongo_odm is a flexible persistence module for any Ruby class to MongoDB.}
  s.test_files = [
    "spec/models/00-blank_slate.rb",
    "spec/models/01-shape.rb",
    "spec/models/02-circle.rb",
    "spec/models/03-big_red_circle.rb",
    "spec/mongo_odm/collection_spec.rb",
    "spec/mongo_odm/config_spec.rb",
    "spec/mongo_odm/core_ext/conversions_spec.rb",
    "spec/mongo_odm/cursor_spec.rb",
    "spec/mongo_odm/document/attribute_methods/dirty_spec.rb",
    "spec/mongo_odm/document/attribute_methods/localization_spec.rb",
    "spec/mongo_odm/document/attribute_methods/query_spec.rb",
    "spec/mongo_odm/document/attribute_methods/read_spec.rb",
    "spec/mongo_odm/document/attribute_methods/write_spec.rb",
    "spec/mongo_odm/document/attribute_methods_spec.rb",
    "spec/mongo_odm/document/callbacks_spec.rb",
    "spec/mongo_odm/document/fields_spec.rb",
    "spec/mongo_odm/document/inspect_spec.rb",
    "spec/mongo_odm/document/persistence_spec.rb",
    "spec/mongo_odm/document/timestamps_spec.rb",
    "spec/mongo_odm/document/validations_spec.rb",
    "spec/mongo_odm/document_spec.rb",
    "spec/mongo_odm/mongo_odm_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<tzinfo>, ["~> 0.3.24"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9.9"])
      s.add_development_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_development_dependency(%q<watchr>, ["~> 0.7"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<tzinfo>, ["~> 0.3.24"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9.9"])
      s.add_development_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_development_dependency(%q<watchr>, ["~> 0.7"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_dependency(%q<activemodel>, ["~> 3.0.3"])
      s.add_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_dependency(%q<bson_ext>, ["~> 1.2.0"])
      s.add_dependency(%q<tzinfo>, ["~> 0.3.24"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_dependency(%q<rcov>, ["~> 0.9.9"])
      s.add_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_dependency(%q<watchr>, ["~> 0.7"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_dependency(%q<activemodel>, ["~> 3.0.3"])
      s.add_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_dependency(%q<bson_ext>, ["~> 1.2.0"])
      s.add_dependency(%q<tzinfo>, ["~> 0.3.24"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_dependency(%q<rcov>, ["~> 0.9.9"])
      s.add_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_dependency(%q<watchr>, ["~> 0.7"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
    s.add_dependency(%q<activemodel>, ["~> 3.0.3"])
    s.add_dependency(%q<mongo>, ["~> 1.2.0"])
    s.add_dependency(%q<bson_ext>, ["~> 1.2.0"])
    s.add_dependency(%q<tzinfo>, ["~> 0.3.24"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<yard>, ["~> 0.6.4"])
    s.add_dependency(%q<rcov>, ["~> 0.9.9"])
    s.add_dependency(%q<rspec>, ["= 2.4.0"])
    s.add_dependency(%q<watchr>, ["~> 0.7"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
    s.add_dependency(%q<activemodel>, ["~> 3.0.3"])
    s.add_dependency(%q<mongo>, ["~> 1.2.0"])
    s.add_dependency(%q<bson_ext>, ["~> 1.2.0"])
    s.add_dependency(%q<tzinfo>, ["~> 0.3.24"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<yard>, ["~> 0.6.4"])
    s.add_dependency(%q<rcov>, ["~> 0.9.9"])
    s.add_dependency(%q<rspec>, ["= 2.4.0"])
    s.add_dependency(%q<watchr>, ["~> 0.7"])
  end
end

